### ISSUE TITLE
Potential incorrect pdfmake CVE

### ISSUE THREAD

**Issue by MrSimmmons** [joaoviictorti/My-CVES#1]
> This snyk report is incorrect. The simulation method is not very well described so that it can be understood.
Report refers to server endpoint /pdf in [pdfmake npm package](https://www.npmjs.org/package/pdfmake), but pdfmake has no such endpoint in release package.

https://github.com/bpampuch/pdfmake/issues/2702#issuecomment-1973447527

Would be great to clarify the CVE this in the mentioned issue if its still valid

**Comment by joaoviictorti** [comment]
Hello @MrSimmmons, I've detailed some information. I'm happy to help.

**Comment by MrSimmmons** [comment]
Yep just saw. Thank you!!
